#!/bin/bash

COLLECTING_PASSWORD=\'$COLLECTING_PASSWORD\'
COLLECTING_RO_PASSWORD=\'$COLLECTING_RO_PASSWORD\'

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER "$COLLECTING_USER";
	ALTER USER "$COLLECTING_USER" WITH PASSWORD $COLLECTING_PASSWORD;
	CREATE DATABASE "$COLLECTING_DB";
	GRANT ALL PRIVILEGES ON DATABASE "$COLLECTING_DB" TO "$COLLECTING_USER";

	CREATE USER "$COLLECTING_USER_RO" WITH PASSWORD $COLLECTING_RO_PASSWORD;
	GRANT CONNECT ON DATABASE "$COLLECTING_DB" to "$COLLECTING_USER_RO";
	GRANT USAGE ON SCHEMA public to "$COLLECTING_USER_RO";
	GRANT SELECT ON ALL TABLES IN SCHEMA public to "$COLLECTING_USER_RO";
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO "$COLLECTING_USER_RO";
EOSQL
